######################################################################
# Automatically generated by qmake (3.0) ? 3? 28 02:22:52 2015
######################################################################

TEMPLATE = app
QT += widgets network

TARGET = lcdsrv
INCLUDEPATH += .

# Input
HEADERS += \
	LcdView.h

SOURCES += \
	main.cpp \
	LcdView.cpp
